openapi: 3.0.0
servers:
  - url: 'http://localhost:3000'
info:
  description: 'Products'
  version: 1.0.0
  title: Product Management
paths:
  /products:
    get:
      tags:
        - product
      summary: Shows all product products
      description: Shows all product
      operationId: getAllProduct
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: string
  '/products/category/{category}':
    get:
      tags:
        - product
      summary: Find product by category
      description: Returns all the products of the given category
      operationId: getProductsBycategory
      parameters:
        - name: category
          in: path
          description: Categories of products
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: string
  '/products/brand/{brand}':
    get:
      tags:
        - product
      summary: Find product by brand
      description: Returns all the products of the given brand
      operationId: getProductsBybrand
      parameters:
        - name: brand
          in: path
          description: Brand of products
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: string
  /insert:
    post:
      tags:
        - product
      summary: Add a new pet to the store
      description: ''
      operationId: addPet
      parameters:
        - in: query
          name: user
          description: The user to create.
          schema:
            type: object
            required:
              - userName
            properties:
              name:
                type: string
              Category:
                type: string
              withtax:
                type: integer
              withouttax:
                type: integer
              Discount:
                type: boolean
              State:
                type: string
              SKV:
                type: string
              Brand:
                type: string
              Media:
                type: string
      responses:
        201:
          description: Created
  /products/SKV:
    get:
      tags:
        - product
      summary: SKV of all products
      description: Returns SKV of all products
      operationId: ViewSKVOfProducts
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: string
  /products/findByStatus:
    get:
      tags:
        - product
      summary: Live/Draft
      description: Multiple status values can be provided with comma separated strings
      operationId: findProductsByStatus
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
              enum:
                - Live
                - Draft
              default: available
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: string
  /product/{pid}:
    delete:
      tags:
        - product
      summary: Deletes a product by product id
      description: ''
      operationId: deletePet
      parameters:
        - name: pid
          in: path
          description: Pet id to delete
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
  /products/retail:
    get:
      tags:
        - product
      summary: Sold Online or Physical
      description: Multiple status values can be provided with comma separated strings
      operationId: findProductByretail
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
              enum:
                - Physical
                - Digital
              default: available
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: string
  /products/discount:
    put:
      tags:
        - product
      summary: Modify Discount of products.
      description: ''
      operationId: modifydiscount
      parameters:
        - in: query
          name: product
          description: The user to create.
          schema:
            type: object
            required:
              - name
            properties:
              SKV:
                type: string
              Discount:
                type: integer
      responses:
        201:
          description: Created
  /products/discounts:
    get:
      tags:
        - product
      summary: Shows all product having discounts.
      description: Shows all product
      operationId: getAllDiscounts
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: string
  '/{SKV}/MRP':
    get:
      tags:
        - product
      summary: gets MRP of a product including taxes and discounts.
      description: Displays MRP, Base Price ,Taxes and Discounts.
      operationId: getMRP
      parameters:
        - name: SKV
          in: path
          description: Brand of products
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: string
  /products/parentchild:
    get:
      tags:
        - product
      summary: All the parent products and their child products
      description: Shows all the parent and child products
      operationId: getParentChild
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: string
  '/{SKV}/Stock':
    get:
      tags:
        - product
      summary: IN STOCK or OUT OF STOCK
      description: Given SKV id it gives the information on weather the product is in stock or out of stock
      operationId: getStock
      parameters:
        - name: SKV
          in: path
          description: Brand of products
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: string
  '/products/{SKV}/variations':
    get:
      tags:
        - product
      summary: Sizes,colors of given product id.
      description: Returns all the variations avalaible of the product.
      operationId: getProductsVariation
      parameters:
        - name: SKV
          in: path
          description: Brand of products
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: string              
  